# docker-compose.yml
version: '3.2'

services:
  web:
    image: ghcr.io/cblunt/jobsapp
    ports:
      - '3000:3000'

  db:
    deploy:
      placement:
        constraints:
          - node.labels.database == true
