version: '3.8'

volumes:
  dbdata:
    driver: local

services:
  db:
    image: postgres:14
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=secret123
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata

  web:
    build: . # Builds the image from Dockerfile
    ports:
      - '3000:3000'
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=secret123
      - HUB_URL=http://chrome:4444
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  css:
    build: . # Use the same application image for this container
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
    tty: true
    volumes:
      - .:/usr/src/app
    command: yarn build:css --watch

  guard:
    build: .
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=secret123
    tty: true
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: bundle exec guard

  chrome:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
