# docker-compose.override.yml
version: '3.2'

services:
  nginx:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx/vhost.development.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - web

  web:
    build: .
    volumes:
      - .:/usr/src/app

  # guard:
  #   build: .
  #   environment:
  #     - RAILS_ENV=development
  #     - RACK_ENV=development
  #     - POSTGRES_USER=rails
  #     - POSTGRES_PASSWORD=secret123
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     - db
  #   command: bundle exec guard --no-bundler-warning --no-interactions
