version: '3.8'

volumes:
  dbdata:
    driver: local

services:
  db:
    image: postgres:14
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=secret123
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata

  web:
    image: jobsapp
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=secret123
      - HUB_URL=http://chrome:4444
    depends_on:
      - db

  css:
    image: jobsapp # Use the same application image for this container
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
    tty: true
    command: yarn build:css --watch

  chrome:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm

  cron:
    image: jobsapp # Use the same application image for this container
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=secret123
    depends_on:
      - db
    command: "/bin/sh -c 'whenever --write-crontab && touch /var/log/cron.log && cron && tail -f /var/log/cron.log'"
