name: Docker Image CI

on:
  push:
    branches:
      - main
      - rails7
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-${{ github.repository }}-docker-layers-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ github.repository }}-docker-layers

      - name: Checkout code from Github
        uses: actions/checkout@v2

      - name: Build and cache Docker Image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: jobsapp:latest
          cache-from: type=local,src=/tmp/docker-cache
          cache-to: type=local,dest=/tmp/docker-cache,mode=max

      - name: Run tests in Docker
        run: |
            if [ -f docker-compose.test.yml ]; then
              docker-compose -f docker-compose.yml -f docker-compose.test.yml run web bin/rails db:create db:schema:load
              docker-compose -f docker-compose.yml -f docker-compose.test.yml run web bin/rails test
            else
              echo "No docker-compose.test.yml file found"
              exit 1
            fi

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    needs:
      - test

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-${{ github.repository }}-docker-layers-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ github.repository }}-docker-layers-

      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/jobsapp:${{ github.sha }}
            ghcr.io/${{ github.repository }}/jobsapp:latest
          cache-from: type=local,src=/tmp/docker-cache # <-- Add cache lines
          cache-to: type=local,dest=/tmp/docker-cache,mode=max
