name: Docker Image CI

on:
  push:
    branches:
      - github-actions
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cache docker build layers
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ github.repository }}-docker-layers

      - uses: actions/checkout@v2

      - name: Load image layers from cache
        run: |
          if [ -f ~/.cache/jobsapp.tar ]; then
            docker load -i ~/.cache/jobsapp.tar
          fi

      - name: Build the Docker image
        run: |
          docker build -t jobsapp:latest .

      - name: Run tests in Docker
        run: |
            if [ -f docker-compose.test.yml ]; then
              docker-compose -f docker-compose.yml -f docker-compose.test.yml run web bin/rails db:create db:schema:load
              docker-compose -f docker-compose.yml -f docker-compose.test.yml run web bin/rails test
            else
              echo "No docker-compose.test.yml file found"
              exit 1
            fi

      - name: Cache the docker image layers
        run: |
          mkdir -p ~/.cache
          docker save -o ~/.cache/jobsapp.tar jobsapp

  publish:
    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - name: Cache docker build layers
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ github.repository }}-docker-layers

      - uses: actions/checkout@v2

      - name: Load image layers from cache
        run: |
          if [ -f ~/.cache/jobsapp.tar ]; then
            docker load -i ~/.cache/jobsapp.tar
          fi

      - name: Publish to Github Container Registry
        uses: docker/build-push-action@v1
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.GCR_PASSWORD }}
            registry: ghcr.io
            repository: cblunt/jobsapp
            cache_froms: jobsapp
            tags: latest
            tag_with_sha: true
