name: Docker Image CI

on:
  push:
    branches:
      - github-actions
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cache docker build layers
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ github.repository }}-docker-layers

      - uses: actions/checkout@v2

      - name: Build application Docker image
        run: |
          if [ -f ~/.cache/jobsapp.tar ]; then
            ls -la ~/.cache
            docker load -i ~/.cache/jobsapp.tar
            docker build --cache-from=jobsapp -t jobsapp .
          else
            docker build -t jobsapp .
          fi

      - name: Build and run tests in Docker
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose -f docker-compose.yml run -e RAILS_ENV=test web bin/rails db:create db:schema:load
            docker-compose -f docker-compose.yml run -e RAILS_ENV=test web bin/rails test
          else
            echo "No docker-compose.test.yml file found"
            exit 1
          fi

      - name: Cache the docker image layers
        run: |
          mkdir -p ~/.cache
          docker save -o ~/.cache/jobsapp.tar jobsapp
          ls -la ~/.cache

  build:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Cache docker build layers
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ github.repository }}-docker-layers

      - uses: actions/checkout@v2

      - name: Build application Docker image
        run: |
          if [ -f ~/.cache/jobsapp.tar ]; then
            ls -la ~/.cache
            docker load -i ~/.cache/jobsapp.tar
            docker build --cache-from=jobsapp -t jobsapp .
          else
            docker build -t jobsapp .
          fi

  publish:
    runs-on: ubuntu-latest

    needs:
      - test
      - build

    steps:
      - name: Cache docker build layers
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ github.repository }}-docker-layers

      - uses: actions/checkout@v2

      - name: Publish application Docker image
        run: |
          ls -la ~/.cache

          if [ -f ~/.cache/jobsapp.tar ]; then
            docker load -i ~/.cache/jobsapp.tar
            docker build --cache-from=jobsapp -t jobsapp .
          else
            docker build -t jobsapp .
          fi

          echo "TBD: This is where the image will be published"
