name: Docker Image CI

on:
  push:
    branches:
      - main
      - rails7
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout code from Github
        uses: actions/checkout@v2

      - name: Build and cache Docker Image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: jobsapp:latest

      - name: Run tests in Docker
        run: |
            if [ -f docker-compose.test.yml ]; then
              docker-compose -f docker-compose.yml -f docker-compose.test.yml run web bin/rails db:create db:schema:load
              docker-compose -f docker-compose.yml -f docker-compose.test.yml run web bin/rails test
            else
              echo "No docker-compose.test.yml file found"
              exit 1
            fi
